<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Aspire" />
        <PackageReference Include="Akka.Cluster.Hosting" />
        <PackageReference Include="Akka.Discovery.Azure" />
        <PackageReference Include="Akka.Discovery.Redis" />
        <PackageReference Include="Akka.Management" />
        <PackageReference Include="Akka.Persistence.Azure.Hosting" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Petabridge.Cmd.Cluster" />
        <PackageReference Include="Petabridge.Cmd.Cluster.Sharding" />
        <PackageReference Include="Petabridge.Cmd.Remote" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebApiTemplate.Domain\WebApiTemplate.Domain.csproj" />
    </ItemGroup>

</Project>
